[connections.smothieConnStr]
account="UVJJQXL-LEB20091"
user="gciaffon"
role="SYSADMIN"
password="Pd907p$n0wFl@k32528"
Warehouse="COMPUTE_WH"
database="SMOOTHIES"
schema="PUBLIC"
client_session_keep_alive=true


