[connections.smothieConnStr]
account="UVJJQXL-LEB20091"
user="gciaffon"
role="SYSADMIN"
password="!Pdg0tpSn0wFl@ke2528"
Warehouse="COMPUTE_WH"
database="SMOOTHIES"
schema="PUBLIC"
client_session_keep_alive=false